[package]
name = "propverify"
version = "0.1.0"
authors = ["Alastair Reid <adreid@google.com>"]
edition = "2018"

[dependencies]
klee-annotations = { path = "../klee-annotations", features = [ "verifier-panic-handler" ] }
